---
version: '3'
services:
  minecraft:
    image: ${MINECRAFT_IMAGE}
    restart: unless-stopped
    env_file:
      - minecraft/server.env
    ports:
      - "2300:2300"
    volumes:
      - minecraft_data:/var/lib/minecraft/world

volumes:
  minecraft_data:
